# Generated by Django 4.1.3 on 2022-11-14 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0004_usersda_userrda_userlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
                ('age', models.FloatField()),
                ('pregnancy', models.CharField(max_length=100, null=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('activity_level', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100, null=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
