# Generated by Django 4.1.3 on 2022-11-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_useinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='calcium',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='calories',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='carbohydrate',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='carotenoids',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='choline',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='copper',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='cysteine',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='dietary_cholesterol',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='fat',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='folate',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='histidine',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='iron',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='isoleucine',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='leucine',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='lysine',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='magnesium',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='manganese',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='methionine',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='niacin',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='pantothenic_acid',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='phenylalanine',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='phosphorus',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='potassium',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='protein',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='riboflavin',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='sat_fat',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='selenium',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='sodium',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='sugar',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='thiamin',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='threonine',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='total_fiber',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='trans_fat',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='tryptophan',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='tyrosine',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='valine',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='vitamin_a',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='vitamin_b_12',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='vitamin_b_6',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='vitamin_c',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='vitamin_d',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='vitamin_e',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='vitamin_k',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='water',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='zinc',
            field=models.FloatField(default=0, null=True),
        ),
    ]
