# Generated by Django 4.1.3 on 2023-01-02 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0008_alter_allfood_saturated_fat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_name', models.CharField(max_length=255)),
                ('measure', models.FloatField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_log_foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
